server {
    listen 8080;
    client_max_body_size 250m;
    location /api/ { proxy_pass http://video-api:8080; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_read_timeout 1200s; }
    location /swagger-ui/ { proxy_pass http://video-api:8080; }
    location /v3/api-docs { proxy_pass http://video-api:8080; }
    location = / { default_type application/json; return 200 '{"service":"FIAP X","docs":"/swagger-ui/index.html"}'; }
}
